version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  telegram:
    build:
      context: .
      dockerfile: ./compose/local/telegram/Dockerfile
    image: sentinel_local_telegram
    depends_on:
      - postgres
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.telegram
      - ./.envs/.local/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: sentinel_production_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
