version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}

services:
  telegram:
    build:
      context: .
      dockerfile: ./compose/production/telegram/Dockerfile
    image: sentinel_production_django
    depends_on:
      - postgres
    env_file:
      - ./.envs/.production/.telegram
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: sentinel_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres
