#!/bin/sh

set -o errexit
set -o nounset

if [ -z "${POSTGRES_USER}" ]; then
    base_postgres_image_default_user='postgres'
    export POSTGRES_USER="${base_postgres_image_default_user}"
fi
export DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"

postgres_ready() {
poetry run python << END
import sys

import asyncio
import asyncpg

async def run():
    try:
        conn = await asyncpg.connect(
            user="${POSTGRES_USER}",
            database="${POSTGRES_DB}",
            password="${POSTGRES_PASSWORD}",
            host="${POSTGRES_HOST}",
            port="${POSTGRES_PORT}",
        )
        await conn.close()
    except ConnectionError:
        sys.exit(-1)
    sys.exit(0)

asyncio.run(run())
END
}

until postgres_ready; do
  >&2 echo 'Waiting for PostgreSQL to become available...'
  sleep 1
done
>&2 echo 'PostgreSQL is available'

poetry install
exec "$@"
